-- Supabase SQL Schema setup for Voice Cloning Runs
-- Run this in your Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS cloning_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    model_name TEXT NOT NULL,
    device TEXT,
    sample_rate INTEGER,
    adapter_params JSONB DEFAULT '{}'::jsonb,
    clip_mappings JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index on session_id for fast queries
CREATE INDEX IF NOT EXISTS idx_cloning_runs_session_id ON cloning_runs(session_id);
